### ISSUE TITLE
Documentation Style

### ISSUE THREAD

**Issue by mingzehuang** [mlysy/LocalCop#10]
Hi, @EFAcar. I checked the vignette of your package. It seems you didn't organize it according to the several parts required in the 'Documentation' section of the checklist. Do you have a package website, or do you mind rearranging your vignette according to the structure required by the checklist? [openjournals/joss-reviews#6744](https://github.com/openjournals/joss-reviews/issues/6744#)

**Comment by EFAcar** [comment]
Hi @mingzehuang.  Here is a list of the items in the Documentation checklist and where they can be found in the package:

- *Statement of need:* Missing (currently only in the manuscript).
- *Installation instructions:* In the [README](https://github.com/mlysy/LocalCop/blob/joss/README.md) file.
- *Example usage:* In the [vignette](https://github.com/mlysy/LocalCop/blob/joss/vignettes/LocalCop-vignette.Rmd).
- *Functionality documentation:* All functions are fully documented in the [man](https://github.com/mlysy/LocalCop/tree/joss/man) folder, which can easily be browsed once the package is installed.
- *Automated tests:* In the [tests/testthat](https://github.com/mlysy/LocalCop/tree/joss/tests/testthat) folder.  These can be run after installing the package using `testthat::test_package("LocalCop")`.  **Note:** we've updated the `devtools::install_github()` command to install the package development version in the README to install the tests as well, so that the `test_package()` command above works.  The README now also contains a section explaining how to run the tests.
- *Community guidelines:* In the [README](https://github.com/mlysy/LocalCop/blob/joss/README.md).

So, would it be OK just to add a "statement of need" to the vignette to satisfy all the Documentation requirements?

**Comment by mingzehuang** [comment]
Sounds great to me @EFAcar !
Once you add the statement of need to the vignette, I'll close this issue:)

**Comment by EFAcar** [comment]
Hi @mingzehuang. The vignette now contains a "statement of need" in the second paragraph of the overview section.

**Comment by mingzehuang** [comment]
Great thanks!
